# Generated by Django 2.2.7 on 2019-11-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldoces',
            name='imagem',
            field=models.ImageField(null=True, upload_to='imagens_de_doces'),
        ),
    ]
